### ISSUE TITLE
AU UI improvements

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#113]
Tracking progress for [rsr/development](/into-cps/intocps-ui/tree/rsr/development)

- [x] Loading progress for Open Project Examples and Open Project from Git
- [x] Co-sim view graf: Change the graf to this: https://github.com/overturetool/tempo-plotting-tool/tree/master/electron
- [x] investigate if Angular 2 can be used only for part of the Application (new project, open*, MM, COE, download manager)
- [ ] Co-Sim view: Variable step size algorithm: **Deadline July 18th**
 - [x] Unique ports in Zero Crossing and Bounded Difference
 - [x] If there is an error in a multi-model then the coe config is empty for some reason. Instead it should be shown that there is an error in the MM or whatever happens.
 - [x] NOT RSR See #81 
 - [ ] NOT RSR Implement validate() on CoSimulationConfig 
 - [x] Warning if changes have been made without saving
 - [x] Launch coe from within view #80.
 - [x] Fix bug with navigating between Angular2 pages of same type. (coe page to another coe page)
 - [x] Ports in constraints should fill space so all text can be seen
 - [x] Hide chart when there is no data.
 - [x] Constraints
 - [x] Remove callback
 - [x] Validate MM before launch
 - [x] Allow collapsing configuration panel.
 - [x] Validate inputs.
 - [x] add MM + co-sim configs to R_ folder when simulation completes
 - [x] Allow accessing COE from outside Angular2.
 - [ ] Replace save dialog with electron tristate dialog
 - [ ] Min max in variable step size
 - [x] Run it through validation when pressing save
- [ ] Multi-model view. **Deadline July 20th**
  - [x] Disallow the user to enter {} in the field.
  - [x] Instance names must not contain periods (.).
  - [x] Types between inputs/outputs must match.
  - [x] Insert {} around FMU keys automatically.
  - [x] Fix bug where parameters of type float are saved as a string.
  - [x] Warning if changes have been made without saving.
  - [x] Collapse button on overview.
  - [x] Update overview after saving new configuration.
  - [x] Flatten the view, using a table like structure
  - [x] Change the column titles for connection modifications while in edit mode. (outputs / inputs)
  - [x] See #45 
  - [x] if an FMU is replaced with another with different scalar variables then the unconfirmed variables are not highlighted, the user will not see that these connections are invalid before switching to the co-sim config page.
  - [x] if an FMU in mm is change to another with different scalar variables an any of the variables that was  previously there were selected in livestream then these keep being there and the user can never remove them. Only current variables are shown so only these can be check/unchecked
  - [x] Validate parameter types.
  - [x] Bug when removing FMU
  - [x] Run it through validation when pressing save
  - [ ] Replace save dialog with electron tristate dialog
  - [x] Show if a given FMU in a MM is supported for the current platform (maybe list all) based on fmu.platforms. #77
  - [x] show error messages on save such that the user can read them while editing the configuration
- [x] Remove menubar for windows except for the main window. **Deadline July 15th**
- [ ] Clearly indicate when a result no longer is reproducible from a given MultiModel+CoSim config using a different icon for the `R_` folder in the project browser. **Deadline July 28th**
 - [ ] Suggestion: use checksum of MM and coe config. This can then be compared the current MM and coe config
- [ ] Enable rename of MM + co-sim config. **Deadline July 21th**
- [ ] Create view for co-simulation experiment. **Deadline July 23th** 
 - [ ] Graf like in Co-Sim view
 - [ ] Eksport of CSV data / download fil.
 - [ ] Show the associated multimodel and coe config.
- [ ] Download manager. **Deadline July 28th**
 - [ ] Download stalls at  99%
 - See #111 
 - [ ] show whats already installed
 - [ ] by default fetch the latest release and show that - https://github.com/into-cps/intocps-ui/issues/111 make it an option to change release version
- [x] Unify the UI layout for MM and co-sim view
- [ ] Clean up in deinitialize: Merge openViewController and menuHandler.deInitialize. Remove openView
- [ ] Try to fix this error. **Deadline July 28th**
![screen shot 2016-06-22 at 11 45 12](https://cloud.githubusercontent.com/assets/2575418/16262221/f7c2b240-386e-11e6-9482-392b7ab8a0b6.png)

**Comment by CThuleHansen** [comment]
The graph should be hidden if there is not any data. Currently it looks a bit like a bug:
![image](https://cloud.githubusercontent.com/assets/3479481/16610888/79c34f80-435e-11e6-9574-8e6c81dbb674.png)

**Comment by lausdahl** [comment]
There is still a bug if you replace an fmu with another with a different interface. (tested with f84ad2b2c380c36aff6413292bba1d2aa2caa0f4) it shows read warning for all old ports but do not show any of the new ones. The idea is to replace the old with the new but if they dont show up it is kind if difficult to achieve.

**Comment by lausdahl** [comment]
The co sim view does not respect the proper datatypes. If a whole number is selected in var step `max step size` then it is send as int `10` and not double `10.0`

**Comment by lausdahl** [comment]
Just created a blank project and new mm with two FMUs added to the project and look:

![screen shot 2016-07-28 at 10 30 15](https://cloud.githubusercontent.com/assets/2575418/17206089/66441118-54ae-11e6-8d6f-262778b27930.png)

no scalar variables! well no wunder that path is all wrong. Where is the root slash

**Comment by lausdahl** [comment]
If I change the path of an FMU why does this not reload the FMU and repopulate it!

**Comment by lausdahl** [comment]
Im closing this as of a6bc5551af4934f56e35100cc4d8dfafa944444a

I spawned a number og new issues for the remaining tasks which can be handled separately or rejected.
